### ISSUE TITLE
npm run tck: TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by m4r71n** [nikku/feelin#24]
__Describe the Bug__

Hi, I've tried to run the DMN-TCK tests with `npm run tck` but there is an error:

```
TypeError: Cannot read properties of undefined (reading 'text')
    at Suite.<anonymous> (file:///home/martin/feelin/test/tck/tck-spec.js:52:38)
    at Object.create (/home/martin/feelin/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/martin/feelin/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.<anonymous> (file:///home/martin/feelin/test/tck/tck-spec.js:33:9)
    at Object.create (/home/martin/feelin/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/martin/feelin/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.<anonymous> (file:///home/martin/feelin/test/tck/tck-spec.js:27:5)
    at Object.create (/home/martin/feelin/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/martin/feelin/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at file:///home/martin/feelin/test/tck/tck-spec.js:17:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
ERROR: "tck:test" exited with 1.
```

__Steps to Reproduce__

```
git clone https://github.com/nikku/feelin.git
git clone https://github.com/dmn-tck/tck.git dmn-tck
cd feelin
npm i
npm run tck
```

__Expected Behavior__

No error

__Environment__

- Host (Browser/Node version), if applicable: Node 18.17.1
- OS: Windows 10 WSL2 Ubuntu 22.04

**Comment by nikku** [comment]
Thanks for opening. Closing via #25 (already had that fix prepared :wink:).

**Comment by m4r71n** [comment]
Awesome thanks!
