### ISSUE TITLE
You cannot use "type":"module" and "require" at the same time!

### ISSUE THREAD

**Issue by Vladqqqqoo** [nikku/feelin#9]
You cannot use "type":"module" and "require" at the same time!
In your package.json file you use "type":"module" and in "index.js" you use `var lezer = require('lezer');`. According to node js documentation it's not appropriate
Useful links:
https://nodejs.org/api/esm.html#esm_introduction
https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\node_modules\feelin\dist\index.js
require() of ES modules is not supported.
require() of C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\node_modules\feelin\dist\index.js from C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\src\services\matrixServices\buildMatrixService.ts is an ES module file as it is a .js file whose ne
arest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\node_modules\feelin\package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Object.require.extensions.<computed> [as .js] (C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\node_modules\ts-node\src\index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\src\services\matrixServices\buildMatrixService.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\work\Projects\BEACON-PROJECTS\forms-manager-server-ts\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

__Steps to Reproduce__

1. Download "0.24.0" version of "feelin" library
2. Import and use it in express application with TS like `import * as feelin from 'feelin'` or `import {
  unaryTest,
  evaluate
} from 'feelin';`
3. Build it

__Expected Behavior__

Should work without errors as in "0.23.0" version

__Environment__

- node 14.16.0
- OS: windows 10
- Library version: 0.24.0

**Comment by nikku** [comment]
We nowadays include scripts that verify TS usage. The issue should be fixed.
